### ISSUE TITLE
CombineReducers should only pass the current reducer's state slice to it

### ISSUE THREAD

**Issue by xqwzts** [johnpryan/redux.dart#10]
Currently `combineReducers` passes the whole app state to each reducer, this adds some overhead where every reducer implementation needs to be aware of the whole app state and return the values of the other reducers as well as the slice of state that it cares about.

For example `counterReducer` here has to return `state.clickCount` although it only cares about `state.count`

```dart
AppState counterReducer(AppState state, action) {
  switch (action) {
    case AppAction.increment:
      return new AppState(state.count + 1, state.clickCount);
```

Similarly `clickCounterReducer` needs to return `state.count` every time though it should really only be handling `state.clickCount`:

```dart
AppState clickCounterReducer(AppState state, action) {
  switch (action) {
    case AppAction.increment:
      return new AppState(state.count, state.clickCount + 1);
```

Whereas if it were to implement combineReducers the way [reduxjs does](http://redux.js.org/docs/api/combineReducers.html) then each reducer would only have to know about it's own slice of state, and can be ignorant of the whole AppState. That would mean counterReducer could look more like this:

```dart
int counterReducer(int state, action) {
  switch(action) {
    case AppAction.increment:
      return state.count + 1;
  ...
}
```

This is probably easier to implement in js since the whole state is basically a map, and each slice of state is tied to a key on the map, which also corresponds to the reducer - being unfamiliar with dart I'm not too sure about how this would be achieved while also allowing custom classes for the state object.

**Comment by Pacane** [comment]
Isn't this meant to be like that so you can clone the state every time when the state is actually an object (or a map)? Otherwise, I suppose you could clone that single "slice", but I doubt the dev tools would be aware of that.

**Comment by xqwzts** [comment]
But this way every reducer is cloning the whole state [and is responsible for cloning the whole state], in my mind we could delegate the `new AppState` statement to `combineReducers` and have each slice make a new object just for that slice - then combine them all in `combineReducers`. Does this make sense?

So what I'm thinking of would look more like this:

```dart
ReducerOneState reducerOne(ReducerOneState state, action) {
  switch(action) {
    case someAction:
      return new ReducerOneState(value: state.value + 1);
  }
}

int reducerTwo(int state, action) {
  switch(action) {
    case anotherAction:
      return state + 1;
  }
} 
```

Where `combineReducers` would call each reducer then combine the results into a new `State`:

```dart
reducerOneState = reducerOne(state.reducerOne, action);
reducerTwoState = reducerTwo(state.reducerTwo, action);

return new AppState(reducerOne: reducerOneState, reducerTwo: reducerTwoState);
```

I'm new to flutter and dart so there's a good chance I'm missing the obvious :)

It's just a quick thought, I'm not sure how one would write a `combineReducers` like that in dart, though I'll find the time to try and implement a basic version soon.

**Comment by brianegan** [comment]
Hey there -- thanks for writing in! I hear what you're saying, and I've been thinking about how to solve this problem as well. 

It's a bit more difficult in Dart b/c we can't just willy-nilly make new objects like we can in JS, but there are a couple of options here that I've thought about that might be better than what we've currently got.

I'll write up a couple options and see whatcha think when I'm back from my vacation next week!

**Comment by xqwzts** [comment]
I put this quick thing together, it always assumes [or forces] the state to be a map keyed by string.

```dart
Reducer combineReducers(Map<String, Reducer> reducers) {
  return (Map<String, dynamic> state, dynamic action) {
    Map<String, dynamic> next = <String, dynamic>{};
    reducers.forEach((key, reducer) => next[key] = reducer(state[key], action));
    return next;
  };
}
```

It requires a bit more overhead in that you have to provide a key for each state slice:

```dart
Reducer appReducer = combineReducers({
  'foo': fooReducer,
  'bar': barReducer,
  'baz': bazReducer,
});
```

But now the reducers are blissfully ignorant of anything outside their own state slice [lessens overhead in the reducer, lessens chances of bugs from repeating or missing the rest of the state in each reducer, allows us to build drop-in reducers that can be shared across projects]

```dart
List<String> fooReducer(List<String> state, action) {
  switch (action['type']) {
    case Actions.addToFoolist:
      List<String> next = <String>[];
      next.addAll(state);
      next.add(action['id']);
      return next;
    case Actions.removeFromFoolist:
      int idx = state.indexOf(action['id']);
      if (idx == -1) {
        return state;
      }

      List<String> next = <String>[];
      next.addAll(state.getRange(0, idx));
      next.addAll(state.getRange(idx + 1, state.length));

      return next;
    default:
      return state;
  }
}

int barReducer(int state, action) {
  switch (action['type']) {
    case Actions.incrementBar:
      return state + 1;
    case Actions.decrementBar:
      return state - 1;
    default:
      return state;
  }
}

...
```

It isn't the most elegant solution, but it brings the behavior closer to redux's combineReducers. I did try to avoid using a map for the state and allow arbitrary classes, but without reflection/mirrors support I'm not really sure how to do that.

**Comment by brianegan** [comment]
Yep, that's totally one solution! I was hoping to keep Strong typing though, and therefore avoid dynamic maps. I believe it will only be possible with Code Generation, though, because of the lack of reflection / mirrors in Flutter. 

That said, rather than using `combineReducers`, you could also write a simple reducer composed of smaller reducers to get what you want:

```dart
// Define your State
class AppState {
  final List<String> items;
  final String searchQuery;

  AppState(this.items, this.searchQuery);
}

// Define your Actions
class AddItemAction {
  String item;
}

class PerformSearchAction {
  String query;
}

// Individual Reducers
List<String> itemsReducer(List<String> items, action) =>
    action is AddItemAction ? (items..add(action.item)) : items;

String searchQueryReducer(String searchQuery, action) =>
    action is PerformSearchAction ? action.query : searchQuery;

// Put em together.
AppState combinedReducer(AppState state, action) => new AppState(
  itemsReducer(state.items, action),
  searchQueryReducer(state.searchQuery, action)
);
```

This is how Reductor (from Java) works. They just generate the code for ya! If this solution is acceptable, we could add this to the README as an example.

I might go ahead and add some code generation steps to this lib in the future, but I was hoping to keep this library as simple as possible, and code generation is still a bit weird in Dart and I'd like to avoid it if possible.

**Comment by xqwzts** [comment]
Thanks, that actually clears things up nicely! I do think it would be very helpful to have in the README.
