### ISSUE TITLE
Store always trigger even state does not change

### ISSUE THREAD

**Issue by johnbland-wf** [johnpryan/redux.dart#14]
https://github.com/johnpryan/redux.dart/blob/master/lib/src/store.dart#L197-L206

```dart
  // The base [NextDispatcher].
  //
  // This will be called after all other middleware provided by the user have
  // been run. Its job is simple: Run the current state through the reducer,
  // save the result, and notify any subscribers.
  _reduceAndNotify(dynamic action) {
    final state = reducer(_state, action);
    _state = state;
    _changeController.add(state);
  }
```

### Issues

1) Changes are always triggered even if the state didn't change
2) The internal state is updated before the stream update is received so validating `state == newState` is equivalent to using `if (1 == 1)`

### Possible Solutions

I'd like to get your thoughts on these two.

**Solution 1**
Keep this as-is, but see swap the order so in our `onChange` handler we can properly compare our states.

**Solution 2**
Remove some of the blackbox so we can extend `Store` with our own implementation to adjust it accordingly to our desired flavor.

### Reasoning

We use [built_value](https://pub.dartlang.org/packages/built_value) for our state. This means any state change will always return a guaranteed new object or the exact same object due to the reducer mutating the immutable.

Through immutability we're able to better control React render cycles which greatly improves performance. With a store always triggering, we have to do internal state checks – where we validate each individual value – negating the inherent equality checks you get from using built_value and, technically, "duplicating" generated code.

Thoughts?

**Comment by johnpryan** [comment]
If I'm understanding correctly, you're saying that `built_value` [generates hashCode and == for you](https://github.com/google/built_value.dart/blob/master/example/lib/values.g.dart#L292) but each Reducer needs to individually check equality when it receives an event from the Dispatcher?

re: solution 1 What do you mean by "swap the order"? Are you saying the event should emit the old state?

re: solution 2 
it's worth considering; Store can be replaced with you're own custom class that uses the rest of the redux.dart api

Do you have a small code sample that can help explain the issue?

**Comment by johnpryan** [comment]
Another option is to dispatch the old state and new state in the same event

**Comment by johnbland-wf** [comment]
> If I'm understanding correctly, you're saying that built_value generates hashCode and == for you

Yes.

> each Reducer needs to individually check equality when it receives an event from the Dispatcher?

No. The reducer just mutates the state using the builder pattern and returns the mutated state.

Ex:
```
myreducer(...) {
  if (action is Blah) return state.rebuild((builder) => builder..myProp = 'new value');
}
```

So a new state object is returned from the reducer.

> re: solution 1 What do you mean by "swap the order"? Are you saying the event should emit the old state?

Swap the last 2 lines of that method so `_state = state;` is after the method dispatches the update.

> re: solution 2
> it's worth considering; Store can be replaced with you're own custom class that uses the rest of the redux.dart api
> 
> Do you have a small code sample that can help explain the issue?

I can work one up for sure.

> Another option is to dispatch the old state and new state in the same event

That definitely works as well. The goal is definitely to have access to both the old and new state to compare.

**Comment by jeroencranendonk-wf** [comment]
Have you considered adding an `identical(state, _state)` condition around the `_changeController.add()` call?

This may cause issues when mutable state is used, but in my opinion when your reducer modifies its input, you're already in a bad situation.

**Comment by johnbland-wf** [comment]
So redux.js does this:

> Redux provides a single store.subscribe method for notifying listeners that the store has updated. Listener callbacks do not receive the current state as an argument—it is simply an indication that something has changed. The subscriber logic can then call getState() to get the current state value.

You don't get the state in `subscribe` at all.

https://redux.js.org/docs/faq/StoreSetup.html#how-do-i-subscribe-to-only-a-portion-of-the-state-can-i-get-the-dispatched-action-as-part-of-the-subscription

It does mention some libraries to compare state:
https://github.com/ashaffer/redux-subscribe
https://github.com/ivantsov/redux-subscriber
https://github.com/jprichardson/redux-watch

Maybe we could do the same here for built_value.

**Comment by brianegan** [comment]
Hey all -- interesting topic! I'm wondering if we can actually take advantage of `Stream`s here to meet your use case? This is one area where having the `state` in the onChange Stream  is really helpful...

For example: Want to only be notified when the state has changed? Use the `distinct` method: 

```
final distinctState = store.onChange.distinct();
``` 

You can even supply your own equals method if you want to, or it will use the `==` method by default.

https://api.dartlang.org/stable/1.24.3/dart-async/Stream/distinct.html

Want to subscribe to a substate? Use the `map` method + `distinct`. 

```
distinctState.map((state) => state.subState).distinct()
```

You can even write your own `StreamTransformer` as well if you need advanced / custom logic! 

Do those solutions work for ya?

**Comment by johnbland-wf** [comment]
Huh...I didn't know about `distinct`. That's quite interesting, @brianegan. I'm going to have to try that out. We were thinking `StreamTransformer` in a simple wrapper, but `distinct` might be enough.

**Comment by johnbland-wf** [comment]
Confirmed `distinct` works. Putting up a simple library for reuse here.

Thx @brianegan @jeroencranendonk-wf @johnpryan. I'll reference it here when it is ready.

**Comment by johnbland-wf** [comment]
Take a look: https://github.com/johncblandii/distinctly-redux.dart.

**Comment by brianegan** [comment]
Nice!

I could see more folks looking for this functionality in the future for sure. Instead of a separate lib, what would you all think about Redux.dart adding a `bool distinct` optional parameter to the constructor? If it's true, we'll use distinct under the hood. If false, we'll emit every time an action is dispatched. It would be `false` by default (so it continues to work as it does now)...

So you'd create your store like this: `new Store(myReducer, distinct: true);`.

PR with this proposed change here: #15
