### ISSUE TITLE
Feedback regarding quickly getting redux up & running

### ISSUE THREAD

**Issue by MichaelRFairhurst** [johnpryan/redux.dart#18]
After the dartconf talk, I decided to get redux running.

I quickly found package:redux, and had the talk quickly in my memory, so I was surprised to hit a few little problems:
* It took me a while to realize that I needed to also use package:flutter_redux. This could be worth putting in bold early on in the readme: "*for use with flutter, use package:flutter_redux which includes this package*".
* Documentation for how redux works, and how flutter_redux works, are kind of fragmented. It makes sense that the *code* should be fragmented, but the *docs* need not be.
* The only available examples are either the counter app (which doesn't even really have any business using redux), or the todo app (which is architected to be absolutely perfect everywhere, making it a real leap to jump into).

As such, I'd recommend making a single example where
* the state is a class (not an int)
* the actions are objects (not an enum)
* the store is passed along via StoreProvider
* the app has multiple routes
* those routes have connections to the store via StoreBuilder and StoreConnector

There are other things that might be worth covering for other people:
* DIY "reselectors"
* true reselectors with the reselect package
* adding the dev tools to the ui
* recommended directory structures for these things

But ultimately, I would recommend as little as possible! Its worth noting, the main examlpe on flutter_redux.dart is really really close to my request :)

Maybe this all exists in a blog post....I tend to search through docs first enough and at a certain completeness threshold (which this project crosses, great job!!) I don't look for blog posts as guides. If the docs are not intended to be as useful as any well-tailored, existing blogposts out there, it would be useful for the docs to link to some of these blogposts.

Speaking of blog posts, I think a lot of the documentation covers "why?" which would probably be better as an external link: "For reasons why flutter developers should consider using redux, consider reading X, Y, Z, Q, articles"

**Comment by johnpryan** [comment]
Thanks for the feedback! - we’ll take closer look at these points as soon
as possible

**Comment by brianegan** [comment]
Great feedback! I'm now on vacation with my family for a week, but will definitely take a look at this when I'm back. Thanks for taking the time to write up such detailed notes.
