### ISSUE TITLE
Exception AppState' is not a subtype of type 'Reducer<AppState>'  when creating a store.

### ISSUE THREAD

**Issue by arturstaszczyk** [johnpryan/redux.dart#27]
Hi, after creating a simple application I get following exception: 

type '(AppState, dynamic) => AppState' is not a subtype of type 'Reducer<AppState>' of 'reducer'.

Here's my setup:

```
dependencies:
  flutter_redux: "^0.5.0"
  redux: "^3.0.0"

@immutable
class AppState {
  final List<double> history;
  final bool screen;

  AppState(this.history, this.screen) {}

  factory AppState.initial() => new AppState(new List.unmodifiable([]), false);
}

AppState appReducer(AppState state, action) {
  return new AppState.initial();
}

final store = new Store<AppState>(
		appReducer,
		initialState: new AppState.initial(),
	);
```

If I change 'AppState' to 'int' in the reducer, the app runs OK.
Is there something wrong with my code?

Cheers,
Artur

**Comment by bgetsug** [comment]
I ran into this issue while studying the examples in https://github.com/brianegan/flutter_architecture_samples, after I upgraded from Flutter 0.2.3 to 0.2.8. Downgrading Flutter back to 0.2.3 resolves it for me.

**Comment by bgetsug** [comment]
I upgraded back to Flutter 0.2.8, then followed the directions here...

- https://github.com/johnpryan/redux.dart#redux-300-migration--dart-2-support
- https://github.com/brianegan/flutter_redux#dart-2-migration-guide

...making changes to https://github.com/brianegan/flutter_architecture_samples/tree/master/example/redux accordingly.

Then I ran `flutter clean` and re-installed the app, and it worked :)

I'm guessing that the most recent versions of Flutter default to Dart 2.

**Comment by brianegan** [comment]
Thanks for the report! Yep, they just released the new beta with Dart 2 on by default. I'll be updating the arch samples shortly :)

**Comment by brianegan** [comment]
@arturstaszczyk Hrm, this is an odd one... If I copy / paste your code directly into a new Flutter project, everything seems to work for me :(

Do you happen to have duplicate `AppState` classes defined in your project or anything like that?

Could you please tell me which version of Flutter you're on (master, beta, etc)? I'm rocking the latest Beta for these tests.

**Comment by brianegan** [comment]
@arturstaszczyk Hey there, any update on this one? Did ya get it working or need more help?

**Comment by brianegan** [comment]
Gonna close this out due to inactivity, but happy to help if ya need anything else :)
