### ISSUE TITLE
Error: Method not found: 'TypedMiddleware'.

### ISSUE THREAD

**Issue by eikebartels** [johnpryan/redux.dart#29]
Hey, 

I get the following error:

```
compiler message: lib/middleware/store_middleware.dart:48:9: Error: Method not found: 'TypedMiddleware'.
compiler message:     new TypedMiddleware<AppState, LoadSchoolsAction>(loadSchools),
```

My code looks like 

```
List<Middleware<AppState>> defaultList = [
    new LoggingMiddleware.printer(),
    new TypedMiddleware<AppState, LoadSchoolsAction>(loadSchools),
]

Middleware<AppState> _createLoadSchools(SchoolRepository repository) {
  return (Store<AppState> store, action, NextDispatcher next) {
    if (action is LoadSchoolsAction) {
       
    }

    next(action);
  };
}
```

And the same happens with `TypedReducer `

```
compiler message: lib/on_boarding/on_boarding_reducer.dart:12:7: Error: Method not found: 'TypedReducer'.
compiler message:   new TypedReducer<OnBoardingState, SchoolsLoadedAction>(_setLoadedSchools),

```
Any idea?

**Comment by brianegan** [comment]
Thanks for writing in... sorry about that trouble.

Hrm, that is odd! I just tested your code on my machine with beta / master branch and unfortunately didn't run into any issues. One question: Are your imports consistent? Meaning do you always `import 'package:my_app/school_repository.dart'`, or do you potentially use something like `import '../school_repository.dart'` in one place and `import 'package:my_app/school_repository.dart'` in another part of your app?

I've noticed the way Dart handles these imports has tripped up a few other folks with odd errors, but I'll admit I'm at a loss as to why it says the method isn't found and I'm not confident that's the proper fix :(

Which version of Dart / Fluter are you using?

**Comment by brianegan** [comment]
Ah wait, I spotted it... you're might be missing a semi-colon at the end of your `defaultList`, or maybe something slightly before that. That's not a great error message :)

For me, when I removed the semi-colon, I got the same error. (I'd added one in since it displayed an error in my IDE).

**Comment by brianegan** [comment]
Hey @eikebartels, did the problem persist or were ya able to get it working? Let me know if I can help out :)

**Comment by brianegan** [comment]
@eikebartels Hey hey :) Any update on this one?

**Comment by eikebartels** [comment]
I guess we can close it :)
