### ISSUE TITLE
Problem with package:todo/redux/actions.dart

### ISSUE THREAD

**Issue by hjonathan** [johnpryan/redux.dart#41]
I want to do my first redux app( redux:3.0.0 & MacOs high Sierra) but I have the next error:

Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Users/jonathan/.pub-cache/hosted/pub.dartlang.org/redux-3.0.0/lib/src/store.dart
...refers, in an import, to the following library:
  package:todo/redux/actions.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

Some idea?

**Comment by johnpryan** [comment]
it looks like lib/src/store.dart is importing `package:todo/redux/actions.dart`... did you accidentally make a modification to the Dart file at `/Users/jonathan/.pub-cache/hosted/pub.dartlang.org/redux-3.0.0/lib/src/store.dart`?

**Comment by hjonathan** [comment]
Nothing
I was creating a new project and when I import redux (import 'package:redux/redux.dart') the error appears

**Comment by hjonathan** [comment]
I deleted the folder /Users/jonathan/.pub-cache/hosted/pub.dartlang.org/redux-3.0.0 
and I executed "flutter packages get" again and every thing is OK
