### ISSUE TITLE
Creating a store with multiple reducers

### ISSUE THREAD

**Issue by dabit3** [johnpryan/redux.dart#43]
I'm curious as to how one would go about creating a store with multiple reducers when using the `combineReducers` method when calling `new Store`?

For instance, if I wanted to pass the entire store down at a top level & have the store available anywhere in my app with all of the reducers.

**Comment by stafyniaksacha** [comment]
Hey @dabit3 you can take a look at the [brianegan/flutter_architecture_samples/.../redux](https://github.com/brianegan/flutter_architecture_samples/tree/master/example/redux) repository 

I think this is what you are looking for: https://github.com/brianegan/flutter_architecture_samples/blob/master/example/redux/lib/reducers/app_state_reducer.dart

**Comment by jordyvandomselaar** [comment]
@stafyniaksacha That page doesn't exist :(

**Comment by brianegan** [comment]
Heya, we have some docs that cover this topic: https://github.com/johnpryan/redux.dart/blob/master/doc/combine_reducers.md
