### ISSUE TITLE
Should docs say todos instead of actions?

### ISSUE THREAD

**Issue by bradyt** [johnpryan/redux.dart#49]
At [041f46/doc/async.md#reducer](https://github.com/johnpryan/redux.dart/blob/041f464ed89184633df346851ac60829fa6e6921/doc/async.md#reducer), the source comments made me pause. Should it say "todos" instead of "actions? That is, at the following:

```dart
// Set our actions to the fetched Todos
// Set our actions to an empty value
```

**Comment by brianegan** [comment]
It certainly should -- good catch, thanks!
