### ISSUE TITLE
Update README.md for Dart 2

### ISSUE THREAD

**Issue by UnHumbleBen** [johnpryan/redux.dart#55]
Commands such as ```pub serve``` in the README do not work in Dart 2. Would be nice if the documentations was updated for Dart 2.

**Comment by md-weber** [comment]
I believe it should be already on Dart 2.0 it maybe has been solved already. I would add that there is currently a unsafe http:// link inside of the readme which reduces the dart points of pub.dev.

**Comment by brianegan** [comment]
Thanks! I think both problems are now fixed :) Appreciate the heads up and PR
