### ISSUE TITLE
ReduxInit action

### ISSUE THREAD

**Issue by aler** [johnpryan/redux.dart#57]
Store doesn't dispatch init action once initialized. Both swift and kotlin redux libs do it.

This action is important to setup app long running services on app startup. 

- [ReSwift](https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Store.swift#L75)
- [Redux-Kotlin](https://github.com/pardom-zz/redux-kotlin/blob/master/lib/src/main/kotlin/redux/Store.kt#L86)

**Comment by brianegan** [comment]
Hey there -- could definitely add something like this in -- in general Redux.js had kept these implementations hidden, and asked users to dispatch their own actions. Would that work for you? I worry about dispatching a new action that folks aren't accounting for.

**Comment by aler** [comment]
I ended up dispatching custom init action manually right after the store has been created in the flutter main func. It might be harder to do it if you init the store through DI or when the store init timing is not well defined.

I found that js lib keeps init as internal and using it is an [anti pattern](https://github.com/reduxjs/redux/pull/140). So I guess it is no go.
