### ISSUE TITLE
Update GitHub homepage to https://pub.dev/packages/redux

### ISSUE THREAD

**Issue by kevmoo** [johnpryan/redux.dart#59]
This is not about changing code – just the GitHub repo settings.

Using the package page is the general contention

**Comment by johnpryan** [comment]
cc: @jeroen-meijer @brianegan @slightfoot

**Comment by slightfoot** [comment]
Thanks. Will check it tomorrow.

**Comment by slightfoot** [comment]
I see you pushed a new version.

**Comment by jeroen-meijer** [comment]
Hi all
Is this still relevant, or can it be closed?

If it's not solved yet, @kevmoo, what home page link are you talking about?
The one in the `pubspec`, or the one listen on the side when visiting the repo here on GitHub?

**Comment by kevmoo** [comment]
![Screen Shot 2020-07-24 at 9 39 43 AM](https://user-images.githubusercontent.com/17034/88414391-9f9c6400-cd91-11ea-924b-d3d829b208a4.png)

**Comment by jeroen-meijer** [comment]
I see, thanks for clarifying.

I can make it the pub link (that is certainly the most common option) but we don't enforce it as such.
It's up to @brianegan and @johnpryan

**Comment by johnpryan** [comment]
I would prefer to change it to the pub link too. I don’t have the permissions to change it, though.

**Comment by jeroen-meijer** [comment]
@johnpryan I see. No problem! I've just made you maintainer for this repo so you should be able to make those kinds of changes yourself in the future. If this is not the case, please let me know. 😁
I also made @brianegan an admin.

@kevmoo I've gone ahead and updated the link. Thanks for the suggestion! 👍🏻

Considering this resolved and closing. If it isn't, feel free to reopen.
