### ISSUE TITLE
Return type in the TypedMiddleware is void

### ISSUE THREAD

**Issue by loposkin** [johnpryan/redux.dart#65]
The middleware has the return type `void` in the TypedMiddleware class

https://github.com/fluttercommunity/redux.dart/blob/3c515fb7bd2371b67492132d9392bf9341104ca7/lib/src/utils.dart#L214-L234

I've expected that after merging #52 `middleware` should have the return type `dynamic`, but this line was not changed. Is it a bug or is there a reason for this behavior?
Possible pull request: #66

**Comment by brianegan** [comment]
It was a bug! I've merged that in. Thanks for the contribution :)
